// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALMZI5HZDW_KZ923bVzel2iE3rlfGFULI',
    appId: '1:382040252144:web:69cb25fb8396f75ca7ac35',
    messagingSenderId: '382040252144',
    projectId: 'fir-app2024-d8815',
    authDomain: 'fir-app2024-d8815.firebaseapp.com',
    storageBucket: 'fir-app2024-d8815.appspot.com',
    measurementId: 'G-297EJ1BT13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFHhhCbhBXtZzD5B5SL58b6OSL4QmnCno',
    appId: '1:382040252144:android:f8cb50fecc101bcba7ac35',
    messagingSenderId: '382040252144',
    projectId: 'fir-app2024-d8815',
    storageBucket: 'fir-app2024-d8815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTfhya1cdiHyvnDCEPHHXcxYuJtBjrYpM',
    appId: '1:382040252144:ios:064dd8b4a61c7aa1a7ac35',
    messagingSenderId: '382040252144',
    projectId: 'fir-app2024-d8815',
    storageBucket: 'fir-app2024-d8815.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
